from utils.include import include
import config
import os
class Handler:
    pass
include(Handler, "./handler/")
urls = [
    ('/', Handler.index.Index),
    ('/api/contest/', Handler.api.contest.Contest),
    ('/api/languages/', Handler.api.language.Languages),
    ('/api/users/', Handler.api.user.Users),
    ('/api/users/(\d+)/', Handler.api.user.User),
    ('/api/users/me/', Handler.api.user.UsersMe),
    ('/api/users/upload/', Handler.api.user.UserUpload),
    ('/api/users/code/', Handler.api.user.UsersCode, {'path': os.path.join(config.DATA_ROOT, 'data/tmp')}),
    ('/api/users/csv/', Handler.api.user.UsersCSV),
    ('/api/users/signin/', Handler.api.user.UserSignIn),
    ('/api/problems/', Handler.api.problem.Problems),
    ('/api/problems/meta/', Handler.api.problem.ProblemsMeta),
    ('/api/problems/(\d+)/', Handler.api.problem.Problem),
    ('/api/problems/(\d+)/pdf/', Handler.api.problem_pdf.ProblemPdf, {'path': os.path.join(config.DATA_ROOT, 'data/problems')}),
    ('/api/problems/(\d+)/meta/', Handler.api.problem.ProblemMeta),
    ('/api/problems/(\d+)/executes/', Handler.api.problem_execute.ProblemExecutes),
    ('/api/problems/(\d+)/rejudge/', Handler.api.rejudge.ProblemRejudge),
    ('/api/problems/(\d+)/testdata/', Handler.api.testdata.Testdata),
    ('/api/problems/(\d+)/testdata/(\d+)/', Handler.api.testdata.Testdatum),
    ('/api/problems/(\d+)/testdata/(\d+)/(\w+)/', Handler.api.testdata_file.TestdatumFile, {'path': os.path.join(config.DATA_ROOT, 'data/testdata')}),
    ('/api/problems/(\d+)/verdict/', Handler.api.problem_verdict.ProblemVerdict),
    ('/api/problems/(\d+)/verdict/file/', Handler.api.problem_verdict.ProblemVerdictFile, {'path': os.path.join(config.DATA_ROOT, 'data/verdicts')}),
    ('/api/problems/zip/', Handler.api.problem_zip.ProblemZip, {'path': os.path.join(config.DATA_ROOT, 'data/problems')}),
    ('/api/submissions/', Handler.api.submission.Submissions),
    ('/api/submissions/(\d+)/', Handler.api.submission.Submission),
    ('/api/submissions/(\d+)/file/', Handler.api.submission.SubmissionFile, {'path': os.path.join(config.DATA_ROOT, 'data/submissions')}),
    ('/api/submissions/(\d+)/rejudge/', Handler.api.rejudge.SubmissionRejudge),
    ('/api/clarifications/', Handler.api.clarification.Clarifications),
    ('/api/clarifications/(\d+)/', Handler.api.clarification.Clarification),
    ('/api/executes/', Handler.api.execute.Executes),
    ('/api/executes/(\d+)/', Handler.api.execute.Execute),
    ('/api/verdicts/', Handler.api.verdict.Verdicts),
    ('/api/system/(\w*)/', Handler.api.system.System),
    ('/api/system/', Handler.api.system.System),
    ('/api/scoreboard/', Handler.api.scoreboard.Scoreboard),
    ('/api/judge/', Handler.api.judge.JudgeSubmission),
    ('/api/judge/testdata/', Handler.api.judge.JudgeSubmissionTestdata),
    ('/api/db/(\w*)/', Handler.api.db.DB),
]
